services:
  database:
    image: postgres
    container_name: streamd_db
    ports:
      - 5431:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: streamd
